version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: yassine124800
      POSTGRES_USER: postgres
      POSTGRES_DB: YAMAY
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    image: yamay-app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  db_data:
